services:
  synq-frontend-local:
    image: node:18-bullseye
    working_dir: /app

    volumes:
      - /Applications/DIC/synquerra/iot-frontend:/app

    ports:
      - "8030:8030"

    environment:
      - NODE_ENV=development
      - VITE_PORT=8030

    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8030"
